image:
  file: .gitpod.Dockerfile
ports:
  - name: Web App
    description: The main application web server
    port: 8080
    onOpen: open-browser
tasks:
  - name: IF server
    command: python3 -m http.server 3000
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
